// src/app/shared/search.service.ts
import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable, map } from 'rxjs';
import { environment } from '../../../../environment/environment';
import { HttpClient } from '@angular/common/http';
import { FoodList } from '../../../interfaces/foodList.interface';
import { Food } from '../../../interfaces/food.interface';

@Injectable({
  providedIn: 'root',
})
export class SearchService {
  private searchSubject = new BehaviorSubject<string>('');
  private baseUrl = environment.apiUrl;
  public search$ = this.searchSubject.asObservable();
  //  public lastSearch = {
  //    maxResult: 10,
  //    pageNumber: 10,
  //    searchTerm: "",
  //    foodList: []
  //  };

  constructor(private _http: HttpClient) {}

  setSearchTerm(term: string) {
    this.searchSubject.next('');
    this.searchSubject.next(term);
  }

  getFoodById(food_id: string): Observable<Food> {
    const response = this._http.get(`${this.baseUrl}/foods/${food_id}`);

    return response as Observable<Food>;
  }

  getFoods(
    searchExpression: string,
    pageNumber: number,
    maxResults: number
  ): Observable<FoodList> {
    const queryParams = {
      search_expression: searchExpression,
      page_number: pageNumber,
      max_results: maxResults,
    };
    const response = this._http.get(`${this.baseUrl}/foods`, {
      params: queryParams,
    });

    return response as Observable<FoodList>;
  }

  getFoodsLocal() {
    return [
      {
        name: 'Whole Milk',
        brand: 'La Serenisima',
        servingSize: '200 ml',
        calories: '114',
        carbohidrates: '9',
        proteins: '6',
        totalFats: '6',
        id: '1',
        category: 'Dairy',
      },
      {
        name: 'Skim Milk',
        brand: 'La Serenisima',
        servingSize: '200 ml',
        calories: '80',
        carbohidrates: '9.6',
        proteins: '6',
        totalFats: '2',
        id: '2',
        category: 'Dairy',
      },
      {
        name: 'Whole Strawberry Yogurt',
        brand: 'La Serenisima',
        servingSize: '190 gr',
        calories: '123',
        carbohidrates: '20',
        proteins: '6.7',
        totalFats: '1.8',
        id: '3',
        category: 'Dairy',
      },
      {
        name: 'Strawberry Yogurt Light',
        brand: 'La Serenisima',
        servingSize: '190 gr',
        calories: '70',
        carbohidrates: '9.8',
        proteins: '7.7',
        totalFats: '0',
        id: '4',
        category: 'Dairy',
      },
      {
        name: 'Granny Smith Apple',
        brand: 'Generic',
        servingSize: '1 medium (182g)',
        calories: '95',
        carbohidrates: '25',
        proteins: '0.5',
        totalFats: '0.3',
        id: '5',
        category: 'Fruit',
      },
      {
        name: 'Banana',
        brand: 'Generic',
        servingSize: '1 medium (118g)',
        calories: '105',
        carbohidrates: '27',
        proteins: '1.3',
        totalFats: '0.4',
        id: '6',
        category: 'Fruit',
      },
      {
        name: 'Chicken Breast',
        brand: 'Tyson',
        servingSize: '100g',
        calories: '165',
        carbohidrates: '0',
        proteins: '31',
        totalFats: '3.6',
        id: '7',
        category: 'Meat',
      },
      {
        name: 'Lean Ground Beef',
        brand: 'Generic',
        servingSize: '100g',
        calories: '250',
        carbohidrates: '0',
        proteins: '26',
        totalFats: '15',
        id: '8',
        category: 'Meat',
      },
      {
        name: 'Salmon Fillet',
        brand: 'Generic',
        servingSize: '100g',
        calories: '208',
        carbohidrates: '0',
        proteins: '20',
        totalFats: '13',
        id: '9',
        category: 'Fish',
      },
      {
        name: 'Tuna in Water',
        brand: 'Starkist',
        servingSize: '1 can (165g)',
        calories: '191',
        carbohidrates: '0',
        proteins: '42',
        totalFats: '1.4',
        id: '10',
        category: 'Fish',
      },
      {
        name: 'Broccoli',
        brand: 'Generic',
        servingSize: '1 cup (91g)',
        calories: '31',
        carbohidrates: '6',
        proteins: '2.6',
        totalFats: '0.3',
        id: '11',
        category: 'Vegetable',
      },
      {
        name: 'Carrot',
        brand: 'Generic',
        servingSize: '1 medium (61g)',
        calories: '25',
        carbohidrates: '6',
        proteins: '0.6',
        totalFats: '0.1',
        id: '12',
        category: 'Vegetable',
      },
      {
        name: 'Almonds',
        brand: 'Blue Diamond',
        servingSize: '1 oz (28g)',
        calories: '164',
        carbohidrates: '6',
        proteins: '6',
        totalFats: '14',
        id: '13',
        category: 'Nuts',
      },
      {
        name: 'Peanut Butter',
        brand: 'Jif',
        servingSize: '2 tbsp (32g)',
        calories: '190',
        carbohidrates: '8',
        proteins: '7',
        totalFats: '16',
        id: '14',
        category: 'Nuts',
      },
      {
        name: 'Oatmeal',
        brand: 'Quaker',
        servingSize: '1 cup (234g)',
        calories: '154',
        carbohidrates: '27',
        proteins: '6',
        totalFats: '3',
        id: '15',
        category: 'Grains',
      },
      {
        name: 'White Rice',
        brand: 'Generic',
        servingSize: '1 cup (158g)',
        calories: '205',
        carbohidrates: '45',
        proteins: '4.3',
        totalFats: '0.4',
        id: '16',
        category: 'Grains',
      },
      {
        name: 'Spaghetti',
        brand: 'Barilla',
        servingSize: '1 cup (140g)',
        calories: '221',
        carbohidrates: '43',
        proteins: '8',
        totalFats: '1.3',
        id: '17',
        category: 'Grains',
      },
      {
        name: 'Whole Wheat Bread',
        brand: 'Nature`s Own',
        servingSize: '1 slice (28g)',
        calories: '69',
        carbohidrates: '12',
        proteins: '3.6',
        totalFats: '1.1',
        id: '18',
        category: 'Grains',
      },
      {
        name: 'Chocolate Chip Cookies',
        brand: 'Chips Ahoy',
        servingSize: '2 cookies (33g)',
        calories: '160',
        carbohidrates: '22',
        proteins: '2',
        totalFats: '8',
        id: '19',
        category: 'Snacks',
      },
      {
        name: 'Potato Chips',
        brand: "Lay's",
        servingSize: '1 oz (28g)',
        calories: '160',
        carbohidrates: '15',
        proteins: '2',
        totalFats: '10',
        id: '20',
        category: 'Snacks',
      },
      {
        name: 'Granola Bar',
        brand: 'Nature Valley',
        servingSize: '1 bar (42g)',
        calories: '190',
        carbohidrates: '29',
        proteins: '3',
        totalFats: '7',
        id: '21',
        category: 'Snacks',
      },
      {
        name: 'Orange Juice',
        brand: 'Tropicana',
        servingSize: '1 cup (240ml)',
        calories: '110',
        carbohidrates: '26',
        proteins: '2',
        totalFats: '0',
        id: '22',
        category: 'Beverages',
      },
      {
        name: 'Cola',
        brand: 'Coca-Cola',
        servingSize: '1 can (355ml)',
        calories: '140',
        carbohidrates: '39',
        proteins: '0',
        totalFats: '0',
        id: '23',
        category: 'Beverages',
      },
      {
        name: 'Green Tea',
        brand: 'Lipton',
        servingSize: '1 cup (240ml)',
        calories: '2',
        carbohidrates: '0',
        proteins: '0',
        totalFats: '0',
        id: '24',
        category: 'Beverages',
      },
      {
        name: 'Vanilla Ice Cream',
        brand: "Ben & Jerry's",
        servingSize: '1/2 cup (100g)',
        calories: '210',
        carbohidrates: '21',
        proteins: '4',
        totalFats: '13',
        id: '25',
        category: 'Desserts',
      },
      {
        name: 'Chocolate Cake',
        brand: 'Generic',
        servingSize: '1 slice (100g)',
        calories: '389',
        carbohidrates: '49',
        proteins: '4.9',
        totalFats: '19',
        id: '26',
        category: 'Desserts',
      },
      {
        name: 'Cheddar Cheese',
        brand: 'Generic',
        servingSize: '1 oz (28g)',
        calories: '113',
        carbohidrates: '0.4',
        proteins: '7',
        totalFats: '9.3',
        id: '27',
        category: 'Dairy',
      },
      {
        name: 'Egg',
        brand: 'Generic',
        servingSize: '1 large (50g)',
        calories: '72',
        carbohidrates: '0.4',
        proteins: '6.3',
        totalFats: '4.8',
        id: '28',
        category: 'Protein',
      },
      {
        name: 'Greek Yogurt',
        brand: 'Chobani',
        servingSize: '1 cup (245g)',
        calories: '137',
        carbohidrates: '9.8',
        proteins: '11',
        totalFats: '5',
        id: '29',
        category: 'Dairy',
      },
      {
        name: 'Avocado',
        brand: 'Generic',
        servingSize: '1 medium (150g)',
        calories: '234',
        carbohidrates: '12.5',
        proteins: '3',
        totalFats: '21',
        id: '30',
        category: 'Fruit',
      },
      {
        name: 'Black Beans',
        brand: 'Goya',
        servingSize: '1 cup (172g)',
        calories: '227',
        carbohidrates: '41',
        proteins: '15',
        totalFats: '0.9',
        id: '31',
        category: 'Legumes',
      },
      {
        name: 'Quinoa',
        brand: 'Generic',
        servingSize: '1 cup (185g)',
        calories: '222',
        carbohidrates: '39',
        proteins: '8',
        totalFats: '3.6',
        id: '32',
        category: 'Grains',
      },
      {
        name: 'Tofu',
        brand: 'Nasoya',
        servingSize: '100g',
        calories: '76',
        carbohidrates: '1.9',
        proteins: '8',
        totalFats: '4.8',
        id: '33',
        category: 'Protein',
      },
      {
        name: 'Hummus',
        brand: 'Sabra',
        servingSize: '2 tbsp (28g)',
        calories: '70',
        carbohidrates: '4',
        proteins: '2',
        totalFats: '6',
        id: '34',
        category: 'Snacks',
      },
      {
        name: 'Apple Juice',
        brand: 'Minute Maid',
        servingSize: '1 cup (240ml)',
        calories: '114',
        carbohidrates: '28',
        proteins: '0.1',
        totalFats: '0.3',
        id: '35',
        category: 'Beverages',
      },
      {
        name: 'Cucumber',
        brand: 'Generic',
        servingSize: '1 medium (201g)',
        calories: '30',
        carbohidrates: '6',
        proteins: '1.3',
        totalFats: '0.2',
        id: '36',
        category: 'Vegetable',
      },
      {
        name: 'Bacon',
        brand: 'Oscar Mayer',
        servingSize: '1 slice (8g)',
        calories: '43',
        carbohidrates: '0.1',
        proteins: '3',
        totalFats: '3.3',
        id: '37',
        category: 'Meat',
      },
      {
        name: 'Butter',
        brand: "Land O'Lakes",
        servingSize: '1 tbsp (14g)',
        calories: '102',
        carbohidrates: '0',
        proteins: '0.1',
        totalFats: '11.5',
        id: '38',
        category: 'Dairy',
      },
      {
        name: 'Orange',
        brand: 'Generic',
        servingSize: '1 medium (131g)',
        calories: '62',
        carbohidrates: '15.4',
        proteins: '1.2',
        totalFats: '0.2',
        id: '39',
        category: 'Fruit',
      },
      {
        name: 'Honey',
        brand: 'Generic',
        servingSize: '1 tbsp (21g)',
        calories: '64',
        carbohidrates: '17',
        proteins: '0.1',
        totalFats: '0',
        id: '40',
        category: 'Sweeteners',
      },
      {
        name: 'Pork Chop',
        brand: 'Generic',
        servingSize: '100g',
        calories: '231',
        carbohidrates: '0',
        proteins: '24',
        totalFats: '14',
        id: '41',
        category: 'Meat',
      },
      {
        name: 'Spinach',
        brand: 'Generic',
        servingSize: '1 cup (30g)',
        calories: '7',
        carbohidrates: '1.1',
        proteins: '0.9',
        totalFats: '0.1',
        id: '42',
        category: 'Vegetable',
      },
      {
        name: 'Bell Pepper',
        brand: 'Generic',
        servingSize: '1 medium (119g)',
        calories: '24',
        carbohidrates: '6',
        proteins: '1',
        totalFats: '0.2',
        id: '43',
        category: 'Vegetable',
      },
      {
        name: 'Pasta Sauce',
        brand: 'Ragu',
        servingSize: '1/2 cup (125g)',
        calories: '70',
        carbohidrates: '10',
        proteins: '2',
        totalFats: '2.5',
        id: '44',
        category: 'Sauces',
      },
      {
        name: 'Blueberries',
        brand: 'Generic',
        servingSize: '1 cup (148g)',
        calories: '84',
        carbohidrates: '21',
        proteins: '1.1',
        totalFats: '0.5',
        id: '45',
        category: 'Fruit',
      },
      {
        name: 'Maple Syrup',
        brand: 'Generic',
        servingSize: '1 tbsp (20g)',
        calories: '52',
        carbohidrates: '13',
        proteins: '0',
        totalFats: '0.1',
        id: '46',
        category: 'Sweeteners',
      },
      {
        name: 'Pineapple',
        brand: 'Generic',
        servingSize: '1 cup (165g)',
        calories: '82',
        carbohidrates: '21.6',
        proteins: '0.9',
        totalFats: '0.2',
        id: '47',
        category: 'Fruit',
      },
      {
        name: 'Beef Jerky',
        brand: "Jack Link's",
        servingSize: '1 oz (28g)',
        calories: '116',
        carbohidrates: '3.1',
        proteins: '9.4',
        totalFats: '7.3',
        id: '48',
        category: 'Snacks',
      },
      {
        name: 'Mango',
        brand: 'Generic',
        servingSize: '1 cup (165g)',
        calories: '99',
        carbohidrates: '25',
        proteins: '1.4',
        totalFats: '0.6',
        id: '49',
        category: 'Fruit',
      },
      {
        name: 'Green Peas',
        brand: 'Generic',
        servingSize: '1 cup (160g)',
        calories: '134',
        carbohidrates: '25',
        proteins: '8.6',
        totalFats: '0.5',
        id: '50',
        category: 'Vegetable',
      },
    ];
  }
}
